netobserv/flowlogs-pipeline

Makefile, pkg/pipeline/extract/extract_aggregate_test.go
This is a follow up to #95 as part of #61
=> Add a test for extract_aggregate

pkg/pipeline/transform/transform_network.go, pkg/pipeline/transform/transform_network_test.go
I noticed that when the expression evaluated in "add_if" contains a scientific notation value like `1.2345e-67`, there's an error like:
```
Cannot transition token types from NUMERIC [1.2345] to VARIABLE [e]
```
The solution I found is to pass the value as a parameter to `Evaluate()`
=> Fix a bug with add_if and scientific notation

.github/workflows/push_image.yml, .github/workflows/release.yml, Makefile, contrib/docker/shortlived.Dockerfile
- an image tagged "main" (tracking branch "main")
- an image, short-lived, tagged after commit SHA
=> Create branch-based and commit-based images

pkg/pipeline/pipeline_builder.go, pkg/pipeline/pipeline_builder_test.go
If a stage is not fully connected, it returns more descriptive messages, indicating which stage is wrongly connected. E.g.:
```
pipeline stage "ingest1": pipeline stage from type "ingest" should send data to at least another stage
pipeline stage "decode1": pipeline stage from type "decode" should receive data from at least another stage
pipeline stage "decode1": pipeline stage from type "decode" should send data to at least another stage
pipeline stage "write1": pipeline stage from type "write" should receive data from at least another stage
```
=> Descriptive error messages on bad pipeline formation

contrib/kubernetes/flowlogs-pipeline.conf.yaml, network_definitions/bandwidth_per_network_service.yaml, network_definitions/bandwidth_per_src_dest_subnet.yaml, network_definitions/bandwidth_per_src_subnet.yaml, network_definitions/connection_rate_per_dest_subnet.yaml, network_definitions/connection_rate_per_src_subnet.yaml, network_definitions/connection_rate_per_tcp_flags.yaml, network_definitions/connections_per_dst_as.yaml, network_definitions/connections_per_src_as.yaml, network_definitions/count_per_src_dest_subnet.yaml, network_definitions/egress_bandwidth_per_dest_subnet.yaml, network_definitions/egress_bandwidth_per_namespace.yaml, network_definitions/geo-location_rate_per_dest.yaml, network_definitions/mice_elephants.yaml, network_definitions/network_services_count.yaml, pkg/pipeline/aggregate_prom_test.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/extract/aggregate/aggregate.go, pkg/pipeline/extract/aggregate/aggregate_test.go, pkg/pipeline/extract/extract_aggregate_test.go, pkg/test/utils.go
This PR:
- Adds fields `recent_op_value` and `recent_count` to the extractor output to be used in prometheus counters
- Adds an integration test between the extractor and prom encoder
It will follow up with PRs to add RawValuesOperation and a filter field to prom encoder config
=> Refactor extractor fields

contrib/kubernetes/flowlogs-pipeline.conf.yaml, docs/api.md, docs/confGenerator.md, network_definitions/bandwidth_per_network_service.yaml, network_definitions/bandwidth_per_src_dest_subnet.yaml, network_definitions/bandwidth_per_src_subnet.yaml, network_definitions/connection_rate_per_dest_subnet.yaml, network_definitions/connection_rate_per_src_subnet.yaml, network_definitions/connection_rate_per_tcp_flags.yaml, network_definitions/connections_per_dst_as.yaml, network_definitions/connections_per_src_as.yaml, network_definitions/count_per_src_dest_subnet.yaml, network_definitions/egress_bandwidth_per_dest_subnet.yaml, network_definitions/egress_bandwidth_per_namespace.yaml, network_definitions/geo-location_rate_per_dest.yaml, network_definitions/mice_elephants.yaml, network_definitions/network_services_count.yaml, pkg/api/encode_prom.go, pkg/confgen/encode.go, pkg/pipeline/aggregate_prom_test.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go, pkg/pipeline/extract/aggregate/aggregate.go, pkg/test/utils.go
Follow-up for #146. Please review that one before this.
=> Add filter field to prometheus encoder

README.md, contrib/kubernetes/flowlogs-pipeline.conf.yaml, docs/api.md, pkg/api/enum.go, pkg/api/transform_generic.go, pkg/confgen/flowlogs2metrics_config.go, pkg/pipeline/pipeline_test.go, pkg/pipeline/transform/transform_generic.go, pkg/pipeline/transform/transform_generic_test.go, pkg/pipeline/transform_multiple_test.go, playground/goflow3.yml
=> Allow transform_generic to keep existing fields

README.md, cmd/flowlogs-pipeline/main.go, hack/update-docs.sh
Also fix doc-gen for podman+selinux
=> NETOBSERV-234 remove slashes in debug json flows

.github/workflows/push_image_pr.yml, .github/workflows/rm-ok-to-test.yaml
Uses the 'ok-to-test' label to trigger the build/push
=> NETOBSERV-229 create pre-merge image on PR via action

pkg/pipeline/encode/encode_prom.go, pkg/pipeline/extract/aggregate/aggregates.go, pkg/pipeline/ingest/ingest_collector.go, pkg/pipeline/ingest/ingest_collector_test.go, pkg/pipeline/ingest/ingest_file.go, pkg/pipeline/ingest/ingest_grpc.go, pkg/pipeline/ingest/ingest_kafka.go, pkg/pipeline/ingest/ingest_kafka_test.go, pkg/pipeline/utils/exit.go, pkg/pipeline/utils/exit_test.go, pkg/pipeline/write/write_loki.go
Some nodes, such as the GRPC+Protobuf server, are not very friendly to shutdown signals from Kubernetes, and may take up to 1 minute before Kubernetes eventually kills the pods. This makes undeployments and redeployments to be very slow.
This PR captures the SIGTERM signals and stops the main goroutine when they are received. The pipeline runs in background so it is automatically stopped when the main goroutine ends.
=> Fix shutdown time

go.mod, go.sum, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/extract/aggregate/aggregates.go, pkg/pipeline/ingest/ingest_collector.go, pkg/pipeline/ingest/ingest_file.go, pkg/pipeline/ingest/ingest_grpc.go, pkg/pipeline/ingest/ingest_kafka.go, pkg/pipeline/ingest/ingest_kafka_test.go, pkg/pipeline/utils/exit.go, pkg/pipeline/utils/exit_test.go, pkg/pipeline/write/write_loki.go
This PR simplifies elegant shutdown by sharing a single channel for all the components that want to listen for a shutdown signal.
Instead of a global variable, ideally this could be achieved by passing a cancellable context to all the running operations but the pipes library is not yet prepared for that (in my to-do list).
=> simplify elegant shutdown

pkg/pipeline/transform/kubernetes/kubernetes.go, pkg/pipeline/transform/transform_network.go
This PR adds HostName when available. 
This will be usefull for topology grouping and ResourceLinks
=> NETOBSERV-253 Enrich Host informations

go.mod, go.sum
cf https://github.com/netsampler/goflow2/issues/80
JIRA: https://issues.redhat.com/browse/NETOBSERV-265
=> NETOBSERV-265 Bump goflow2, add support for ms-based time

README.md, contrib/kubernetes/flowlogs-pipeline.conf.yaml, docs/api.md, hack/deploy-and-monitor-k8s-network-workload.sh, network_definitions/config.yaml, pkg/api/api.go, pkg/api/ingest_collector.go, pkg/confgen/flowlogs2metrics_config.go, pkg/pipeline/ingest/ingest_collector.go, pkg/test/e2e/pipline/flp-config.yaml
Fixes #200
@eranra @KalmanMeth 
Is it ok with you to have a breaking changes here? (people who used legacy v5 now have to configure it explicitly)
If that's a problem, we could default to the previous behaviour (legacy port = main port +1) and have another setting to disable v5, but I think it's more simple to keep default as 0 = legacy disabled.
=> NETOBSERV-341 configure netflow v5 separately (breaking change if using v5)

pkg/api/conn_track.go, pkg/api/enum.go, pkg/pipeline/conntrack/aggregator.go, pkg/pipeline/conntrack/aggregator_test.go, pkg/pipeline/conntrack/conn.go, pkg/pipeline/conntrack/conntrack.go, pkg/pipeline/conntrack/conntrack_test.go, pkg/pipeline/conntrack/hash.go, pkg/pipeline/conntrack/hash_test.go, pkg/pipeline/conntrack/utils_test.go
This PR adds the basic functionality of connection tracking.
Currently it outputs only new connection records and flow logs records.
Notes:
- There are still missing parts that will be added in later PRs such as adding the hash field in the output records,  reporting on connection status/end and deleting ended connections
- I struggled finding names for the identifiers (methods, variables, etc) and deciding what should be exported (PascalCase). Please advice on better names.
- ~~Once #201 is merged, this PR should be rebased.~~
=>  Add basic functionality of connection tracking

pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go, pkg/pipeline/extract/aggregate/aggregate.go, pkg/pipeline/extract/aggregate/aggregate_test.go, pkg/pipeline/extract/aggregate/aggregates.go, pkg/pipeline/transform/connection_tracking/connection_tracking.go, pkg/pipeline/transform/connection_tracking/connection_tracking_test.go, pkg/pipeline/utils/lru.go, pkg/pipeline/utils/timed_cache.go, playground/prom1.yml
Refactor multiple instances of LRU cache into shared code.
=> Common cache with expiry time

pkg/config/config.go, pkg/config/generic_map.go, pkg/pipeline/write/write_loki.go
This fix `fatal error: concurrent map iteration and map write` when calling `stdout` and `loki` stages in parallel
=> NETOBSERV-334 concurrent map iteration & write fix

go.mod, go.sum, pkg/api/conn_track.go, pkg/pipeline/conntrack/conn.go, pkg/pipeline/conntrack/conntrack.go, pkg/pipeline/conntrack/conntrack_test.go, pkg/pipeline/conntrack/hash.go
- Add a connection store that stores the connections sorted by last update time
- Add a dependency on github.com/benbjohnson/clock to allow mocking time
Notes for reviewer:
- Please start reviewing from the added tests
- Does `connectionStore` deserve a file of its own?
=> conntrack: Implement connection end records

pkg/pipeline/conntrack/aggregator.go, pkg/pipeline/conntrack/conn.go, pkg/pipeline/conntrack/conntrack.go, pkg/pipeline/conntrack/hash.go, pkg/pipeline/conntrack/hash_test.go
This PR changes the type under the hood of the hash from `[]byte` to `uint64`.
`uint64` simplifies the code since its easier to copy than `[]byte` and can serve as a key in a map (in contrast to `[]byte`)
This PR is a follow up on the 2nd point from this review: https://github.com/netobserv/flowlogs-pipeline/pull/220#discussion_r893270514
I also changed the hash to use 64 bits instead of 32 bits to reduce the chance of collisions (different connections with the same hash).
Assuming a perfect hash function with uniform distribution of the has values,
for 32 bits we need only 9,300 connections to have 1% chance for collision.
But, for 64 bits we need ~61,000,000 connections to have 1% chance for collision.
I based this on the table from [Birthday …
=> Refactor hashType: []byte -> uint64

pkg/api/conn_track.go, pkg/api/decode_aws.go, pkg/api/encode_kafka.go, pkg/api/encode_prom.go, pkg/api/extract_aggregate.go, pkg/api/ingest_collector.go, pkg/api/ingest_grpc.go, pkg/api/ingest_kafka.go, pkg/api/transform_filter.go, pkg/api/transform_generic.go, pkg/api/transform_network.go, pkg/api/write_stdout.go, pkg/config/pipeline_builder_test.go
We recently started using the config API in the NOO to configure FLP.
Some attributes do not have the omitempty flag resulting in them getting converted in json with an empty string or 0 as value instead of using the internal default value of FLP.
=> Add omitempty flag to stage config

pkg/pipeline/encode/encode_kafka.go, pkg/pipeline/ingest/ingest_collector.go
3 different things in this patch:
- kafka configuration tuning for performances
- transformer wrapper error handling
- fix ingestor_collector bug when out channel is full resulting in the ingester sending single batch flow while many flows are waiting
=> Kafka ingestor fix

pkg/pipeline/decode/decode_json.go, pkg/pipeline/decode/decode_json_test.go
If a flow is directly ingested by the kafka transformer instance (e.g. the eBPF agent submits there directly), it needs to add the `TimeReceived` field as soon as it unmarshalls the flow data.
=> NETOBSERV-258: add TimeReceived in Kafka transformer

pkg/api/ingest_kafka.go, pkg/pipeline/ingest/ingest_kafka.go, pkg/pipeline/ingest/ingest_kafka_test.go
Multiple small changes in this PR:
- Fix timer in kafka ingester which was causing the FLP transformer to stop processing flows under too much traffic
- Add batch limit in kafka ingester
- Fix concurrent map access that could cause some crash when loglevel was set to debug
- Expose Kafka commit interval and default to 500ms for performances
=> Netobserv 390: fix kafka transformer

.github/workflows/pull_request.yml, .github/workflows/pull_request_e2e.yml, Makefile
Fix a typo that caused the golang 1.18 bad linting workaround not to
work.
Even if linting is partially disabled, add 1.18 to the CI.
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
=> Makefile: fix support for golang 1.18

pkg/api/conn_track.go, pkg/pipeline/conntrack/conntrack.go, pkg/pipeline/conntrack/conntrack_test.go, pkg/pipeline/conntrack/utils_test.go
This PR adds 2 fields to the output records of the connection tracking module:
1. connection hash id as a string in hex format (internally, it's stored as uint64 so it's size is 8 bytes)
2. RecordType with 3 value options: `NewConnection`, `EndConnection`, `FlowLog`.
=> Conntrack: Add RecordType and HashId fields

contrib/kubernetes/flowlogs-pipeline.conf.yaml, docs/metrics.md, network_definitions/connection_rate_per_dest_subnet.yaml
In this pr I have just fixed network definition for aggregate destination connection count
Fixes #242
=> Fixed network definition for aggregate dest conn count

cmd/confgenerator/main.go, docs/confGenerator.md, network_definitions/bandwidth_per_network_service.yaml, network_definitions/bandwidth_per_src_dest_subnet.yaml, network_definitions/bandwidth_per_src_subnet.yaml, network_definitions/connection_rate_per_dest_subnet.yaml, network_definitions/connection_rate_per_src_subnet.yaml, network_definitions/connection_rate_per_tcp_flags.yaml, network_definitions/connections_per_dst_as.yaml, network_definitions/connections_per_src_as.yaml, network_definitions/count_per_src_dest_subnet.yaml, network_definitions/egress_bandwidth_per_dest_subnet.yaml, network_definitions/egress_bandwidth_per_namespace.yaml, network_definitions/flows_length_histogram.yaml, network_definitions/geo-location_rate_per_dest.yaml, network_definitions/loki_bandwidth_per_namespace.yaml, network_definitions/loki_logs_per_sec.yaml, network_definitions/network_services_count.yaml, pkg/confgen/confgen.go, pkg/confgen/config.go, pkg/confgen/doc.go, pkg/confgen/flowlogs2metrics_config.go
Include only extract-aggregate and encode-prom rules in the produced config file.
=> adjustments to confgenerator for Operator

docs/api.md, pkg/api/write_stdout.go, pkg/pipeline/write/write_stdout.go
Add a new format to `write_stdout` module called `fields` that can be used to print tabulated output which is slightly easier to read than raw json or text outputs.
=> Add tabulated output to write_stdout

cmd/flowlogs-pipeline/main.go
Read config errors were silently ignored, now catch & log them
=> Catch read config error

go.mod, go.sum
I created a pull request in the prometheus/common repository:
https://github.com/prometheus/common/pull/394
Meanwhile, this PR change the dependency to point to our local fork so we can marshall/unmarshall loki HTTP config without Proxy errors.
=> Temporary use forked prometheus/common to fix ProxyURL unmarshalling

pkg/pipeline/ingest/ingest_grpc.go, pkg/pipeline/ingest/ingest_kafka.go, pkg/pipeline/ingest/ingest_kafka_test.go, pkg/test/utils.go
Added more metrics to the kafka ingester and added timeout mecanics to the kafka tests.
=> NETOBSERV-465: Kafka metrics 2

pkg/pipeline/extract/aggregate/aggregate.go, pkg/pipeline/extract/aggregate/aggregate_test.go
Addresses #265 
https://issues.redhat.com/browse/NETOBSERV-490
=> enable individual labels from aggregate

pkg/api/utils_test.go, pkg/confgen/confgen_test.go, pkg/confgen/config.go
Using `yaml.UnmarshalStrict()` will prevent us from making typos in our yamls without being noticed.
=> Make yaml.Unmarshal strict

README.md, docs/api.md, pkg/api/transform_network.go, pkg/pipeline/transform/transform_network.go, pkg/pipeline/transform/transform_network_test.go
Fixes #275 
Signed-off-by: Kuldeep Singh Pal <tkuldeep.allen@gmail.com>
=> Added assign_if transformation

contrib/kubernetes/flowlogs-pipeline.conf.yaml, docs/metrics.md, pkg/confgen/confgen.go, pkg/confgen/confgen_test.go, pkg/confgen/encode.go, pkg/confgen/extract.go, pkg/confgen/transform.go, pkg/confgen/visualization.go, pkg/config/config.go, pkg/config/config_test.go, pkg/test/e2e/pipline/flp-config.yaml, pkg/test/utils.go
Unmarshaling non-config related json still use the non-strict version.
This is a follow-up on #271 
Fix #274
=> Make unmarshaling json config strict

README.md, docs/api.md, pkg/api/transform_filter.go, pkg/pipeline/transform/transform_filter.go, pkg/pipeline/transform/transform_filter_test.go
Add to Transform Filter the ability to filter out flow logs based on whether a certain field is equal or not equal to some value.
This functionality is needed by Palmetto to filter out flow logs that do or do not satisfy some condition (such as direction of the flow).
=> Add to Transform Filter to support remove_entry_if_equal and remove_entry_if_not_equal

docs/api.md, pkg/api/encode_prom.go, pkg/config/pipeline_builder_test.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go
This enable TLS configuration for the prometheus endpoint
=> NETOBSERV-396: Expose TLS configuration for prometheus endpoint

cmd/apitodoc/main.go, cmd/apitodoc/main_test.go, docs/api.md
This PR enhances the apitodoc script to parse struct pointers in the API such as in the following cases:
https://github.com/netobserv/flowlogs-pipeline/blob/9b96359be572c2b9d0fcf5620d5be3386f8a955d/pkg/api/ingest_kafka.go#L30
https://github.com/netobserv/flowlogs-pipeline/blob/9b96359be572c2b9d0fcf5620d5be3386f8a955d/pkg/api/encode_prom.go#L30
=> Make apitodoc support Ptrs and update docs

.gitleaks.toml
cf https://github.com/leaktk/fake-leaks/blob/main/.gitleaks.toml
Context: I've got a security alert triggered because of the fake certificates used there in tests.
We need to add this `gitleak` config file to mark that as false positive
=> Add fake TLS keys to scan ignore list

pkg/pipeline/transform/transform_network.go
Currently, FLP logs show loads of these "Can't find service name for Port 57430 and protocol 6" logs
Problem is that they don't really refer to issues, it's totally expected to have unmatched ports (especially when looking at source ports). The fact that this is logged within the processing pipeline loop make them unsuitable for `Info` level.
This PR moves them to Debug level.
=> Log as debug: "Can't find service name for..."

contrib/kubernetes/flowlogs-pipeline.conf.yaml, network_definitions/bandwidth_per_src_subnet.yaml
This PR uses the timebased TopK feature in the standard metrics produced by flp. The relevant metric is flp_bandwidth_per_source_subnet, with Topk=5, showing the 5 subnets with the most traffic in the most recent minute.
=> added TopK to bandwidth_per_src_subnet

cmd/flowlogs-pipeline/main_test.go, pkg/api/transform_network.go, pkg/pipeline/transform/kubernetes/kubernetes-mock.go, pkg/pipeline/transform/kubernetes/kubernetes.go, pkg/pipeline/transform/transform_network.go
"failed to initialize pipeline opening "": open : no such file or directory"
Previous PR removed the default file names for service mapping
=> Fix crash on startup

pkg/pipeline/transform/kubernetes/kubernetes.go, pkg/pipeline/transform/kubernetes/kubernetes_test.go, pkg/pipeline/transform/transform_network_test.go
This PR adds a Transformer for each Kubernetes informer that converts the watched Pods, Services, and Nodes to `Info` instances, that are stored by the informers cache and contain only the data that is required for the decoration.
This also alleviates the load on the Garbage Collector: before this patch, a new `Info` instance was created for each flow decoration. Now the same objects are reused on `GetInfo` invocations for the same IP.
In Flowlogs-Pipelines with mid-to-low loads, no improvements have been observed in terms of CPU and slight improvements in terms of memory. In the image below, the middle part corresponds to the new version of FLP.
=> NETOBSERV-578: decrease informers' memory consumption

pkg/pipeline/transform/kubernetes/kubernetes.go
This is a minor change that maybe will have 0 impact.. But I've found a weird case where node's flows are sometimes assigned an empty string namespace, and other times namespace is undefined. This is very weird and I don't know why there is this discrepancy, maybe something wrong on the loki side? (since this field is used for indexing).
It ends up duplicating metrics in the console, and make it harder to work with in the console.
=> Remove namespace for nodes

docs/operational-metrics.md, pkg/pipeline/ingest/ingest_grpc.go, pkg/pipeline/ingest/ingest_kafka.go, pkg/pipeline/ingest/metrics.go
This removes it as a summary of batch sizes
Batch sizes can however still be figured out, via "Flows processed / Batch size in bytes count"
@memodi this PR restores `netobserv_ingest_flows_processed` as it was before, so it should fix your grafana dashboard without you having anything to do
=> NETOBSERV-633 Restore ingest_flows_processed as a simple counter

Makefile
CGO it's not required and usually makes executables more resource-consuming. It also adds some extra requirements to the build/test pipeline (e.g. having to have GCC + libraries, etc...)
Reference read: https://dave.cheney.net/2016/01/18/cgo-is-not-go
=> disable CGO

go.mod, go.sum, pkg/config/config.go, pkg/pipeline/conntrack_integ_test.go, pkg/pipeline/pipeline_builder.go, vendor/github.com/netobserv/gopipes/pkg/node/node.go, vendor/github.com/netobserv/gopipes/pkg/node/options.go, vendor/modules.txt
Updated to version 0.2.0 of go-pipes and allow defining the length of the internal buffers between pipeline stages.
=> Allow defining buffer length of internal nodes

pkg/pipeline/write/write_loki.go, pkg/pipeline/write/write_loki_test.go
Changing the JSON encoder of Loki:
* Do not sort fields alphabetically
* Do not escape HTML (it still escapes JSON strings)
The improvements in terms of CPU are sensible:
=> Speedup Loki JSON serialization

README.md, contrib/dashboards/dashboard_details.json, contrib/dashboards/dashboard_manual_locations_on_map.json, contrib/dashboards/dashboard_totals.json, contrib/dashboards/jsonnet/dashboard_details.jsonnet, contrib/dashboards/jsonnet/dashboard_totals.jsonnet, contrib/kubernetes/flowlogs-pipeline.conf.yaml, docs/metrics.md, docs/operational-metrics.md, network_definitions/config.yaml, network_definitions/connection_rate_per_src_subnet.yaml, network_definitions/connections_per_dst_as.yaml, network_definitions/connections_per_src_as.yaml, network_definitions/count_per_src_dest_subnet.yaml, network_definitions/geo-location_rate_per_dest.yaml, network_definitions/loki_bandwidth_per_namespace.yaml, network_definitions/network_services_count.yaml, pkg/confgen/flowlogs2metrics_config.go
This PR changes the metrics that rely on connections to use the connection tracking
~~I have an issue with fixing [geo-location_rate_per_dest.yaml](https://github.com/netobserv/flowlogs-pipeline/blob/c4e2f41fc0f7d720b97e5d1d2033fc17e8aaf48c/network_definitions/geo-location_rate_per_dest.yaml)
The problem is that I need to add `dstLocation_CountryName` to the connection tracking key fields of `dst`:~~
https://github.com/netobserv/flowlogs-pipeline/blob/c4e2f41fc0f7d720b97e5d1d2033fc17e8aaf48c/network_definitions/config.yaml#L49-L52
~~But, there is no symmetric `srcLocation_CountryName` to add to the `src` section.~~
~~Adding a field to the `dst` section with no symmetric field in the `src` section will cause the grouping of flow-logs into connections to stop working in the bi-directional …
=> Change metrics to use connection tracking

pkg/config/generic_map.go, pkg/config/generic_map_test.go
The GenericMap's Copy method is run in diverse stages of the pipeline, for each processed flow.
Preallocating the map size to the expected resulting size can improve Copy CPU performance and memory allocations by 40%-50%.
Benchmark results with 20-entries maps (before vs after):
```
BenchmarkGenericMap_Copy-12       658083              1671 ns/op            1852 B/op          2 allocs/op
BenchmarkGenericMap_Copy-12       978686              1082 ns/op            1199 B/op          1 allocs/op
```
Benchmark results with 30-entries maps (before vs after):
```
BenchmarkGenericMap_Copy-12       354102              3280 ns/op            4337 B/op          4 allocs/op
BenchmarkGenericMap_Copy-12       633978              1758 ns/op            2324 B/op          1 allocs/op
```
=> Improving performance of generic map copy

pkg/pipeline/write/write_loki.go
Loki write use a goroutine to do async send to loki.
This is unnecessary because loki client is already doing async send.
I tested this change under some load and did not see any impact.
=> Remove unnecessary goroutine of loki writer

README.md, pkg/api/conntrack.go, pkg/pipeline/conntrack_integ_test.go, pkg/pipeline/extract/conntrack/conn.go, pkg/pipeline/extract/conntrack/conntrack.go, pkg/pipeline/extract/conntrack/conntrack_test.go, pkg/pipeline/extract/conntrack/utils_test.go
This PR adds the `_IsFirst` field to connection records (`newConnection`, `updateConnection` and `endConnection`).
It's not added to `flowLog` records.
The field is set to true only on the first record of the connection.
It is useful in cases where `newConnection` records are not outputted (to reduce the number output records)
and there is a need to count the total number of connections: simply counting `_IsFirst=true`
This solves #298
=> conntrack: Add `_IsFirst` field

pkg/pipeline/transform/transform_network.go, pkg/pipeline/transform/transform_network_test.go
This caused that empty-string and nil namespaces were treated differently in some metrics aggregations:
Now there are no duplicities:
=> NETOBSERV-666: K8s decoration not adding namespace if empty

pkg/pipeline/transform/transform_network.go
When we have a location enrichment failure, we currently isue an error, which fills the log with error messages on each faulty flow log. We were requested to change this to a warning, so that it doesn't flood the error log.
=> change error to warning

README.md, cmd/flowlogs-pipeline/main.go, contrib/kubernetes/flowlogs-pipeline.conf.yaml, docs/api.md, pkg/api/encode_prom.go, pkg/confgen/flowlogs2metrics_config.go, pkg/config/config.go, pkg/operational/health.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/health_test.go
* Make `address` field as configurable for prom server.
* Make health address as configurable similar to port.
Fixes #349
Signed-off-by: Kuldeep Singh Pal <tkuldeep.allen@gmail.com>
=> Made prom and health server url configurable

README.md, docs/api.md, network_definitions/config.yaml, pkg/api/transform_generic.go, pkg/pipeline/transform/transform_generic.go, pkg/pipeline/transform/transform_generic_test.go
This PR allows to add in the configuration file a multiplier to apply to particular fields in a flow log.
For example, if we know that we only get a sampling of the flow logs (e.g. 1/20), then the administrator may want us to multiply the measured number of bytes and/or packets in the flow log entries in order to get a closer estimate of the actual number of bytes and/or packets.
Each field that requires a multiplier must be individually marked.
This PR implements this functionality in the transform-generic stage.
=> implemented multiplier in transform-generic

pkg/api/transform_network.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go, pkg/pipeline/extract/aggregate/aggregate.go, pkg/pipeline/extract/aggregate/aggregate_test.go, pkg/pipeline/extract/aggregate/aggregates.go, pkg/pipeline/extract/aggregate/aggregates_test.go, pkg/pipeline/transform/transform_network.go, pkg/pipeline/transform/transform_network_direction.go, pkg/pipeline/transform/transform_network_test.go, pkg/pipeline/utils/timed_cache.go
JIRA: https://issues.redhat.com/browse/NETOBSERV-386
Allows to configure IP ranges and assign them any name
IPs falling in those ranges are flagged with that name
=> NETOBSERV-386 IP categorization

.github/workflows/pull_request.yml, .github/workflows/release.yml, Makefile, contrib/docker/Dockerfile, hack/update-docs.sh
This update the Dockerfile to make it possible to cross build FLP container image.
Example of manual cross build command:
`podman buildx build --platform=linux/ppc64le -t test -f ./contrib/docker/Dockerfile .`
Could someone with docker installed could confirm that the cli API is identical and the example above also works with docker?
=> Updated Dockefile for crosscompilation compatibility

docs/api.md, docs/operational-metrics.md, pkg/api/conntrack.go, pkg/api/encode_prom.go, pkg/api/extract_aggregate.go, pkg/config/pipeline_builder_test.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/prom_cache_test.go, pkg/pipeline/extract/aggregate/aggregate_test.go, pkg/pipeline/extract/aggregate/aggregates.go, pkg/pipeline/extract/conntrack/conntrack.go, pkg/pipeline/extract/conntrack/conntrack_test.go, pkg/pipeline/utils/timed_cache.go, pkg/test/utils.go
The memory usage of FLP seems to grow linearly with the number of concurrent connections being handled at the same time.
For encode_prom, state is saved (both in FLP and in the prometheus Go client) for each metric/labels combination that is reported. This results in memory growth that is linear with respect to the number of connections currently identified as active. In a configuration with limited memory resources it is desirable to instruct FLP to limit the amount of memory usage.
The tradeoff would be to not report on new connections once the memory limit is hit.
The conntrack stage memory usage also grows with the number of connections and should have the possibility of limiting the number of connections tracked.
=> limit memory used by FLP

README.md, contrib/kubernetes/flowlogs-pipeline.conf.yaml, docs/api.md, network_definitions/config.yaml, pkg/api/conntrack.go, pkg/pipeline/extract/conntrack/conn.go, pkg/pipeline/extract/conntrack/conntrack.go, pkg/pipeline/extract/conntrack/conntrack_test.go, pkg/pipeline/extract/conntrack/store.go, pkg/pipeline/extract/conntrack/utils_test.go
Fixes #370 
This PR should be merge after #357
=> Rename updateConnection -> heartbeat

pkg/config/generic_map.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/extract/conntrack/aggregator.go, pkg/pipeline/extract/conntrack/aggregator_test.go, pkg/pipeline/extract/conntrack/conn.go, pkg/pipeline/extract/conntrack/conntrack.go, pkg/pipeline/extract/conntrack/conntrack_test.go, pkg/pipeline/extract/conntrack/hash_test.go, pkg/pipeline/extract/conntrack/utils_test.go, pkg/pipeline/extract/timebased/filters.go, pkg/utils/convert.go
This PR skip duplicates in connection tracking aggregations.
It rely on `Duplicate` field [provided by eBPF agent](https://github.com/netobserv/netobserv-ebpf-agent/pull/66)
=> NETOBSERV-838 Group ingress+egress flows in same connection

pkg/pipeline/extract/conntrack/store.go
This is a small optimization for the `getConnection()` method.
Normally, the record of a connection is stored in one of the scheduling groups.
Given the hash id of a connection, retrieving its record comprises of 2 steps:
1. retrieving the scheduling group.
2. retrieving the record from the scheduling group.
This PR avoids the second step when the scheduling group isn't found in the first step.
=> Avoid searching new connections in the multi-ordered-map

pkg/test/e2e/pipline/flp-config.yaml
Since the prometheus port moved from encode_prom to metricsSettings, the e2e test that uses this field must be updated.
=> fix e2e test

.github/workflows/pull_request.yml
cc @eranra @ronensc @KalmanMeth 
I'm not sure who initialized the codecov action, I think Eran?
But afaik the codecov secret [is only required for private repos](https://github.com/codecov/codecov-action#arguments), and moreover, I don't think it is actually set in this workflow because "[GitHub’s standard pull_request workflow trigger by default prevents write permissions and secrets access to the target repository.](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)".
=> Remove unused (?) codecov secret

pkg/pipeline/transform/kubernetes/cni/ovn_kubernetes.go, pkg/pipeline/transform/kubernetes/cni/ovn_kubernetes_test.go
The format of this annotation has changed between ocp 4.12 and 4.13 This kind of IPs are typically used in host-network traffic
=> NETOBSERV-924 adapt to new ovn annotation format

pkg/pipeline/extract/conntrack/conn.go, pkg/pipeline/extract/conntrack/conntrack.go, pkg/pipeline/extract/conntrack/conntrack_test.go
When implementing the swapAB logic I missed the fact that in addition to swapping the values of the connection source and destination, their hashes should be swapped as well. Without this, aggregates such as `Bytes_AB` and `Bytes_BA` would be wrong.
I realized that I had the same bug in the unit test the was supposed to test it.
This PR fixes the problem and the test.
Once merged, this will allow us to spot connections that their source and destination were swapped by inspecting their `newConnection` record. The `Bytes_AB` would be 0 while `Bytes_BA` would be >0.
=> conntrack: Fix a bug in swapAB

pkg/config/pipeline_builder.go, pkg/config/pipeline_builder_test.go, pkg/config/stage_params.go
@jotak @jpinsonneau , as we spoke:
This PR adds the write ipfix stage under the FLP pipeline builder in order to be used by the operator. The methods are reachable by the operator code this way. I tested by replacing the source while I made the changes.
Changes:
- Add WriteIpfix to pipeline_builder.go
- Add NewWriteIpfixParams to stage_params
=> NETOBSERV-962 - ADD write ipfix stage to pipeline builder

README.md, contrib/kubernetes/flowlogs-pipeline.conf.yaml, docs/api.md, docs/operational-metrics.md, network_definitions/config.yaml, pkg/api/conntrack.go, pkg/pipeline/conntrack_integ_test.go, pkg/pipeline/extract/conntrack/aggregator.go, pkg/pipeline/extract/conntrack/aggregator_test.go, pkg/pipeline/extract/conntrack/conn.go, pkg/pipeline/extract/conntrack/conntrack.go, pkg/pipeline/extract/conntrack/conntrack_test.go, pkg/pipeline/extract/conntrack/hash_test.go, pkg/pipeline/extract/conntrack/metrics.go, pkg/pipeline/extract/conntrack/store.go, pkg/pipeline/extract/conntrack/utils_test.go
Backport of https://github.com/netobserv/flowlogs-pipeline/pull/413/commits/0ea48c54365562e6c18b887679a7e68df9c425f1
As these changes impact [NETOBSERV-973](https://issues.redhat.com/browse/NETOBSERV-973), we decided to backport for [release-1.2](https://github.com/netobserv/flowlogs-pipeline/tree/release-1.2)
=> [Backport] Conntrack output field copy operations + fix duplicates

README.md, contrib/kubernetes/flowlogs-pipeline.conf.yaml, docs/api.md, docs/operational-metrics.md, network_definitions/config.yaml, pkg/api/conntrack.go, pkg/pipeline/conntrack_integ_test.go, pkg/pipeline/extract/conntrack/aggregator.go, pkg/pipeline/extract/conntrack/aggregator_test.go, pkg/pipeline/extract/conntrack/conn.go, pkg/pipeline/extract/conntrack/conntrack.go, pkg/pipeline/extract/conntrack/conntrack_test.go, pkg/pipeline/extract/conntrack/hash_test.go, pkg/pipeline/extract/conntrack/metrics.go, pkg/pipeline/extract/conntrack/store.go, pkg/pipeline/extract/conntrack/utils_test.go
This PR brings `first` and `last` operations for connection tracking `OutputFields` in order to be able to keep first flow direction informations as:
```go
OutputFields: []api.OutputField{
...
{
Name:      "FlowDirection",
Operation: "first",
},
{
Name:      "IfDirection",
Operation: "first",
},
{
Name:      "AgentIP",
Operation: "first",
},
},
```
Also fix duplicates:
- ~~[bypasing these on top of Extract loop](https://github.com/netobserv/flowlogs-pipeline/pull/413/files#diff-ad9d7ad5fe71050e459358c0cd62a24d04733e5607adef15fbe15ea37e099ffbR65-R69) that can generate multiple connection events~~ => https://github.com/netobserv/flowlogs-pipeline/pull/421
- [keeping terminating connection](https://github.com/netobserv/flowlogs-pipeline/pull/413/files#diff-949ee8972308321191c5cac4ea0dc6d786a8 …
=> Conntrack output field copy operations + fix duplicates

docs/operational-metrics.md, pkg/pipeline/extract/conntrack/aggregator.go, pkg/pipeline/extract/conntrack/aggregator_test.go, pkg/pipeline/extract/conntrack/conntrack.go, pkg/pipeline/extract/conntrack/conntrack_test.go, pkg/pipeline/extract/conntrack/hash.go, pkg/pipeline/extract/conntrack/hash_test.go, pkg/pipeline/extract/conntrack/metrics.go, pkg/pipeline/extract/conntrack/store.go, pkg/test/utils.go
This PR adds the following operational metrics that count errors during hash computation and in the aggregators.
```
conntrack_aggregator_errors{error="MissingFieldError",field="Bytes"} 11
conntrack_aggregator_errors{error="Float64ConversionError",field="Bytes"} 22
conntrack_hash_errors{error="MissingFieldError",field="Missing"} 33
```
=> conntrack: Add operational metrics on errors for hash computation and aggregators

pkg/pipeline/decode/decode_protobuf.go, pkg/pipeline/ingest/ingest_grpc.go, pkg/pipeline/ingest/ingest_kafka.go
Rely on `TimeFlowEndMs` for kafka delay as the `Decode` function returns a GenericMap that doesn't contains `TimeFlowEnd`.
Related PRs:
https://github.com/netobserv/flowlogs-pipeline/pull/203/files
https://github.com/netobserv/network-observability-console-plugin/pull/153/files
=> NETOBSERV-984 - KafkaInterBrokerProtocalVersion throws warning and has ingestion errors

pkg/pipeline/ingest/ingest_grpc.go, pkg/pipeline/ingest/ingest_kafka.go
Errors are provided as metrics only to minimize the impact on resources, and logs readability, when an error is thrown repeatedly.
=> Remove error logs in processing loop

.github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, .mk/shortcuts.mk, Makefile, contrib/docker/shortlived.Dockerfile
- Can trigger workflow from branch workflow-test
- Make default multi-arch to single amd64
- Remove specific ci targets; make shortlive builds more straightforward
- Disambiguate makefile env vs workflow env
- Remove unused targets
- Remove now unused shortlived dockerfile
=> Update workflow, setup workflow-test

hack/examples/ipfix-collector/ipfix-dump.go, pkg/pipeline/write/write_ipfix.go
Fixes the issue https://github.com/netobserv/flowlogs-pipeline/issues/405
=> Fix naming of k8s entries to ipfix export

README.md, docs/api.md, pkg/config/pipeline_builder.go, pkg/config/stage_params.go
This PR simply add `EncodeS3` to pipeline builder.
PS: it seems that doc was not up to date so it also update it
=> Add encode s3 to pipeline builder

.mk/development.mk, README.md, docs/api.md, pkg/api/encode_prom.go, pkg/confgen/confgen_test.go, pkg/config/pipeline_builder_test.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go, pkg/test/network_defs.go
Improve the promEncode API to allow setting multiple filters. To avoid breaking change, the existing filter API is kept and marked as deprecated.
Operator PR: https://github.com/netobserv/network-observability-operator/pull/387
=> NETOBSERV-1131: need to allow setting multiple filters

pkg/operational/metrics.go
If we use multiple encode_prom stages, each instance tries to register its operational metrics. This results in a prometheus.AlreadyRegisteredError, which is not really an error, so we convert it to a warning.
=> changed error to warning

pkg/pipeline/encode/encode_prom_test.go
@KalmanMeth here's a test that clarifies the behaviour that IMO we should keep, wrt to missing labels and https://github.com/netobserv/flowlogs-pipeline/pull/460
=> Add test for missing labels

docs/api.md, pkg/api/conntrack.go, pkg/pipeline/decode/decode_protobuf.go, pkg/pipeline/extract/conntrack/aggregator.go, pkg/pipeline/extract/conntrack/aggregator_test.go, pkg/pipeline/extract/conntrack/conn.go, pkg/pipeline/extract/conntrack/utils_test.go
Following https://github.com/netobserv/flowlogs-pipeline/pull/451 we removed unused fields to the genericMap by default.
Aggregators on connection tracking needs to be updated to:
- avoid reporting unecessary errors
- be able to keep last provided field
This PR introduce a new `ReportMissing` field optional to allow error reporting on aggregations.
Please let me know if you want to have a different default behavior or a more flexible solution.
=> NETOBSERV-1208 & NETOBSERV-1233 Aggregators skip missing fields

pkg/pipeline/decode/decode_protobuf.go
OVS drop support just merged upstream
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/tree/net/openvswitch/drop.h
=> NETOBSERV-1135: add ovs subsystem drop causes

README.md, contrib/kubernetes/flowlogs-pipeline.conf.yaml, network_definitions/bandwidth_per_network_service.yaml, network_definitions/bandwidth_per_src_dest_subnet.yaml, network_definitions/bandwidth_per_src_subnet.yaml, network_definitions/connection_length_histogram.yaml, network_definitions/connection_rate_per_dest_subnet.yaml, network_definitions/connection_rate_per_src_subnet.yaml, network_definitions/connection_rate_per_tcp_flags.yaml, network_definitions/connections_per_dst_as.yaml, network_definitions/connections_per_src_as.yaml, network_definitions/count_per_src_dest_subnet.yaml, network_definitions/egress_bandwidth_per_dest_subnet.yaml, network_definitions/egress_bandwidth_per_namespace.yaml, network_definitions/flows_length_histogram.yaml, network_definitions/geo-location_rate_per_dest.yaml, network_definitions/network_services_count.yaml, pkg/api/encode_prom.go, pkg/confgen/flowlogs2metrics_config.go
Following the feedback of @aslom in #473:
1. The README was updated to run `make ocp-deploy` with `IMAGE_ORG=netobserv`
2. The configuration of FLP was updated. #418 introduced a new API field in `extract_aggregate` which required this update.
3. On the way, updated the operational metric prefix to `flp_op_` (added underscore) to avoid metric names like `flp_opmetrics_processed`
=> Update README and config

.github/pull_request_template.md
FYI @KalmanMeth @ronensc , not sure if you were aware of this planned change: we're adding this PR template to help guiding contributors through the processes, across all repos used in operator context.
=> NETOBSERV-1222: create PR template

cmd/flowlogs-pipeline/main.go, pkg/pipeline/encode/encode_kafka.go, pkg/pipeline/extract/aggregate/aggregate.go, pkg/pipeline/extract/aggregate/aggregate_test.go, pkg/pipeline/extract/timebased/filters.go, pkg/pipeline/ingest/ingest_kafka.go, pkg/pipeline/ingest/ingest_synthetic.go, pkg/pipeline/write/write_ipfix.go
Some weaknesses were detected, fixing here a bunch of them, especially inconsistent null-checks or suppressed errors
n/a
=> Fixes a couple of minor weaknesses

docs/api.md, pkg/api/encode_prom.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go
This PR improve prom metrics filtering introducing:
=> NETOBSERV-1352 enhance prom filters for RTT metrics

docs/api.md, pkg/api/encode_prom.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go
Backport of https://github.com/netobserv/flowlogs-pipeline/pull/478
This is necessary for fixing [NETOBSERV-1344](https://issues.redhat.com/browse/NETOBSERV-1344)
no-doc / no-qe on this PR: actual changes are on the operator PR https://github.com/netobserv/network-observability-operator/pull/456
=> NETOBSERV-1344 enhance prom filters for RTT metrics [1.4 backport]

pkg/pipeline/transform/kubernetes/kubernetes.go, vendor/k8s.io/client-go/metadata/metadatainformer/informer.go, vendor/k8s.io/client-go/metadata/metadatainformer/interface.go, vendor/k8s.io/client-go/metadata/metadatalister/interface.go, vendor/k8s.io/client-go/metadata/metadatalister/lister.go, vendor/k8s.io/client-go/metadata/metadatalister/shim.go, vendor/modules.txt
This is follow up to the work @jpinsonneau started in https://github.com/jpinsonneau/flowlogs-pipeline/tree/update_metainformer
- switch to metadata informer for RS
=> NETOBSERV-1247: using Meta informer for replicaSets

docs/api.md, pkg/api/api.go, pkg/api/encode_prom.go, pkg/api/enum.go, pkg/config/pipeline_builder_test.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_metric.go, pkg/pipeline/encode/encode_prom_test.go
- New ValueScale config to allow scale conversion, e.g. RTT ns to seconds
- To avoid having reserved characters or words in filters, use a dedicated API instead: new setting Filter.Type (exact,presence,absence or regex)
- Pre-compute regex by setting up a "predicate" function per filter
**Breaking-change** : metrics currently defining filters such as "FlowDirection: 0|2" must be adapted with the new Filter Type API
n/a
=> NETOBSERV-1231: Improve promencode API: scaling & filters

cmd/flowlogs-pipeline/main.go, pkg/api/encode_prom.go, pkg/confgen/flowlogs2metrics_config.go, pkg/config/config.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go, pkg/pipeline/utils/prom_server.go
At present, all prometheus metrics go to the same port defined globally (:9102).
This PR allows to have multiple prometheus encode stages, each one reporting its metrics via a different port (and/or address).
Default behavior is to continue to report metrics via the globally defined port.
Existing configurations should continue to work without change.
n/a
If not, you can ignore the rest of this checklist.
=> Allow multiple prometheus stages with different URLs

pkg/confgen/flowlogs2metrics_config.go, pkg/config/config.go
It's panic'ing with:
panic: runtime error: invalid memory address or nil pointer dereference
Due to ConnectionInfo being a pointer
n/a
=> Fix crash when metrics settings are unset

docs/api.md, pkg/api/api.go, pkg/api/transform_network.go, pkg/pipeline/transform/transform_network.go
Add Kubernetes Infra transform rule
Related operator PR:
https://github.com/netobserv/network-observability-operator/pull/517
=> NETOBSERV-1244: Add Kubernetes Infra transform rule

pkg/api/transform_network.go, pkg/pipeline/transform/kubernetes/kubernetes.go, pkg/pipeline/transform/transform_network.go, pkg/pipeline/transform/transform_network_test.go
Zones are added to the flows if the rule is configured with the new addZone bool.
n/a
=> NETOBSERV-1203: Added option to add zones in k8s transform rule

pkg/pipeline/transform/location/location.go, pkg/pipeline/transform/location/location_test.go
- Do not use Insecure TLS
- Add client timeout
- Unexport a few variables
n/a
=> NETOBSERV-1308: fix minor vulnerabilities with location db

Makefile, pkg/pipeline/write/testnorace/write_ipfix_test.go, pkg/pipeline/write/write_ipfix.go, pkg/pipeline/write/write_ipfix_test.go
- Adding a test for the IPFIX exporter
- Small refactoring to remove some boilerplate code and have all fields more easily accessible
cc @bhale , I believe this test can help you when adding more ipfix fields
=> Add test on IPFIX writer

pkg/pipeline/write/testnorace/write_ipfix_test.go, pkg/pipeline/write/write_ipfix.go
I am working on implementing a fix for 
https://github.com/netobserv/flowlogs-pipeline/issues/544
There are many new fields added to the pipeline but not yet written via IPFIX. I attempted to start with a single field and get feedback before I added several fields using a bad approach. 
None
** I am not familiar with the processes **
=> Add new field to ipfix exporter for flowRtt

go.mod, go.sum, pkg/pipeline/pipeline_test.go, pkg/pipeline/write/testnorace/write_ipfix_test.go, pkg/pipeline/write/write_ipfix.go, vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/decode/decode_protobuf.go, vendor/modules.txt
See eBPF update https://github.com/netobserv/netobserv-ebpf-agent/pull/275 and followup to remove Duplicate field https://github.com/netobserv/netobserv-ebpf-agent/pull/276
Update go mod once eBPF PR is merged
=> NETOBSERV-1466 Update eBPF dependency for FLP

pkg/pipeline/write/testnorace/write_ipfix_test.go, pkg/pipeline/write/write_ipfix.go
- refactor IPFIX fields mapping / definition
- allow optional fields
- add interfaces and directions (plural) fields to IPFIX template
- add tests for partial records & non-enriched records
n/a
=> NETOBSERV-1566: ipfix: make RTT optional

docs/api.md, pkg/api/transform_network.go, pkg/pipeline/transform/transform_network.go, pkg/pipeline/transform/transform_network_test.go
- rename IPCategories -> SubnetLabels
- allow to skip applying labels when a given field is present (in order
to save space / processing by avoiding redundant information)
- Adapt to refactored API (cf #580)
E.g., if you have some "add_ip_category" rule defined such as:
```yaml
transform:
type: "network"
network:
rules:
- input: "the_address"
output: "subnet"
type: add_ip_category
ipCategories:
- cidrs:
- 101.1.0.0/32
- 100.1.0.0/16
name: "MySite.com"
```
This must be rewritten as:
```yaml
transform:
type: "network"
network:
rules:
- type: add_subnet_label
add_subnet_label:
input: "the_address"
output: "subnet"
subnetLabels:
- cidrs:
- 101.1.0.0/32
- 100.1.0.0/16
name: "MySite.com"
```
#580 (merged)
If you are not familiar with our processes or don't know what to answer in the list below, …
=> NETOBSERV-1426: subnet labelling enhancements

cmd/flowlogs-pipeline/main.go, pkg/config/config.go, pkg/config/pipeline_builder.go, pkg/pipeline/encode/encode.go, pkg/pipeline/encode/encode_kafka.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go, pkg/pipeline/encode/encode_s3.go, pkg/pipeline/encode/metrics_common.go, pkg/pipeline/encode/opentelemetry/encode_otlplogs.go, pkg/pipeline/encode/opentelemetry/encode_otlpmetrics.go, pkg/pipeline/encode/opentelemetry/encode_otlptrace.go, pkg/pipeline/pipeline.go, pkg/pipeline/pipeline_builder.go, pkg/pipeline/pipeline_watcher.go, pkg/pipeline/transform/kubernetes/informers/informers.go, pkg/utils/kubernetes.go
Added new type to watch a configmap and notify prometheus encoder
n/a
=> NETOBSERV-1427: Added config watcher and supporting metrics reloading

pkg/pipeline/encode/metrics_common.go
Skip all `RecordKeyMissing` and consider these as `0` since we removed empty fields from eBPF agent.
https://github.com/netobserv/netobserv-ebpf-agent/blob/release-1.5/pkg/decode/decode_protobuf.go#L61-L67
If this needs to be configurable for specific cases please let me know. 
n/a
=> NETOBSERV-1597: skip RecordKeyMissing error

README.md, pkg/config/pipeline_builder.go, pkg/config/stage_params.go
This is just background code not requiring testing:
- add otel to pipeline builder
- unrelated readme update
n/a
=> NETOBSERV-1522 Add otel to pipeline builder

.github/workflows/pull_request.yml, .github/workflows/pull_request_e2e.yml, .github/workflows/push_image.yml, .github/workflows/push_image_pr.yml, .github/workflows/release.yml, .golangci.yml, contrib/docker/Dockerfile
=> NETOBSERV-1707: move to go 1.22

README.md, docs/api.md, pkg/api/transform_filter.go, pkg/config/pipeline_builder_test.go, pkg/pipeline/transform/transform_filter.go, pkg/pipeline/transform/transform_filter_test.go
Note this PR is based on 2 other non-merged PRs - commit https://github.com/netobserv/flowlogs-pipeline/commit/ae226f9826f46df792cd78174c8a87b80eebcafe is the significant one
- New "remove_entry_all_satisfied" filter type: entry is removed only if
all the conditions (represented by nested rules) are satisfied. This
allows to have logical AND in filter conditions, whereas previously it
was only possible to have logical OR
- New "conditional_sampling" filter type: allows to have random sampling
based on conditions. For example, a flow matching conditions A and B
may have a sampling ratio of 1:10 whereas a flow matching condition C
has 1:100 sampling and all other flows are 1:1
- Introduced a "preprocess" function on rules; currently it's only used
to be able to cast the `Value interface{}` …
=> Add new filters allowing FLP-based dedup

pkg/pipeline/encode/opentelemetry/opentelemetry.go, pkg/pipeline/utils/timed_cache.go
```
Attributes:
-> timeflowstart: Int(1720623609511)
-> destination.k8s.name: Str(ip-10-0-1-172.ec2.internal)
-> dns.errno: Int(0)
-> source.mac: Str(02:BF:1A:CD:98:51)
-> host.direction: Int(0)
-> destination.mac: Str(02:60:C1:E6:97:15)
-> destination.k8s.kind: Str(Node)
-> protocol: Int(17)
-> source.k8s.name: Str(ip-10-0-1-125.ec2.internal)
-> source.k8s.kind: Str(Node)
-> destination.address: Str(10.0.1.172)
-> timereceived: Int(1720623613)
-> bytes: Int(124)
-> interface.directions: Slice([0,0])
-> timeflowend: Int(1720623609511)
-> source.k8s.host.name: Str(ip-10-0-1-125.ec2.internal)
-> destination.k8s.owner.kind: Str(Node)
-> destination.k8s.host.name: Str(ip-10-0-1-172.ec2.internal)
-> source.k8s.node.name: Str(ip-10-0-1-125.ec2.internal)
-> source.port: Int(45558)
-> …
```
=> NETOBSERV-1522 & NETOBSERV-1750 FLP otel fixes

pkg/pipeline/aggregate_prom_test.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go, pkg/pipeline/encode/metrics_common.go, pkg/pipeline/extract/conntrack/aggregator_test.go, pkg/pipeline/extract/conntrack/conntrack_test.go, pkg/pipeline/extract/conntrack/hash_test.go, pkg/pipeline/extract/timebased/tables.go, pkg/pipeline/transform/transform_filter.go, pkg/pipeline/utils/timed_cache.go, pkg/prometheus/prom_server.go, pkg/test/prom.go, pkg/utils/convert.go
- Use dedicated prom registries per prom-encode stage
- restart registry when a "illegal" change is detected (change in labels), since this is not allowed by the prom client, even if unregsitering the metric first
- There's also a small perf improvement by using utils.ConvertToString instead of fmt.Sprintf
n/a
=> NETOBSERV-1748: restart prom registry on metrics breaking change

cmd/confgenerator/main.go, pkg/pipeline/extract/aggregate/aggregate.go, pkg/pipeline/extract/conntrack/conn.go, pkg/pipeline/transform/kubernetes/enrich.go, pkg/pipeline/transform/transform_filter.go, pkg/pipeline/transform/transform_network.go
=> NETOBSERV-1799: Use converToString insted of Sprintf

.tekton/flowlogs-pipeline-pull-request.yaml, .tekton/flowlogs-pipeline-push.yaml, hack/update-build.sh
Added update-build script to add downstream labels
n/a
=> NETOBSERV-1792: Added update-build script to add downstream labels

docs/api.md, pkg/api/encode_prom.go, pkg/confgen/confgen_test.go, pkg/config/pipeline_builder_test.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_metric.go, pkg/pipeline/encode/encode_prom_test.go, pkg/pipeline/encode/metrics_common.go, pkg/pipeline/encode/opentelemetry/encode_otlpmetrics.go
- New "remap" field in MetricItem API
- New struct to distinguish source labels (from flow logs) and target labels (to use in metrics)
- Operator: https://github.com/netobserv/network-observability-operator/pull/733
=> NETOBSERV-1772: allow prom label remapping

.tekton/flowlogs-pipeline-pull-request.yaml, .tekton/flowlogs-pipeline-push.yaml, Makefile, contrib/docker/Dockerfile, hack/update-build.sh
Fixing multiarch build.
Addressing multiple konflux error:
- the build not being hermetic
- removing deprecated task in the build
- using base image from registry.redhat.io
=> Addressing konflux error and fixing multi arch build with podman 5.2

hack/update-build.sh
Add description label to downstream container image, this is required by konflux.
n/a
=> NETOBSERV-1633 : Add description label to downstream container image

.tekton/flowlogs-pipeline-pull-request.yaml, .tekton/flowlogs-pipeline-push.yaml
Enable prefetch konflux task.
n/a
=> NETOBSERV-1633: Enable prefetch in konflux

.golangci.yml, Makefile, README.md, cmd/apitodoc/main.go, docs/operational-metrics.md, pkg/api/encode_s3.go, pkg/confgen/confgen.go, pkg/confgen/doc.go, pkg/confgen/grafana_jsonnet.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_metric.go, pkg/pipeline/encode/metrics_common.go, pkg/pipeline/encode/opentelemetry/opentelemetry.go, pkg/pipeline/extract/aggregate/aggregate.go, pkg/pipeline/extract/aggregate/aggregates.go, pkg/pipeline/extract/conntrack/conntrack_test.go, pkg/pipeline/extract/timebased/filters.go, pkg/pipeline/extract/timebased/timebased.go, pkg/pipeline/transform/kubernetes/enrich.go, pkg/pipeline/transform/location/location_test.go, pkg/pipeline/transform/transform_generic.go, pkg/pipeline/write/grpc/grpc_test.go, pkg/pipeline/write/testnorace/write_ipfix_test.go, pkg/pipeline/write/write_ipfix.go, pkg/pipeline/write/write_loki.go, pkg/test/e2e/utils.go, pkg/test/utils.go
Bumped golangci-lint from v1.56.2 to v1.61.0
n/a
Sorry, just fixing local build errors.
=> Bumped golangci-lint from v1.56.2 to v1.61.0

docs/api.md, pkg/api/encode_prom.go, pkg/confgen/confgen_test.go, pkg/config/pipeline_builder_test.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go, pkg/pipeline/encode/metrics/filtering.go, pkg/pipeline/encode/metrics/flattening.go, pkg/pipeline/encode/metrics/preprocess.go, pkg/pipeline/encode/metrics/preprocess_test.go, pkg/pipeline/encode/metrics_common.go, pkg/pipeline/encode/opentelemetry/encode_otlpmetrics.go, pkg/pipeline/extract/aggregate/aggregate.go, pkg/pipeline/ingest/ingest_grpc.go, pkg/pipeline/write/write_loki.go
This makes it possible to generate metrics with labels/filters set on list fields (e.g. interfaces) and nested fields (e.g. soon-coming structured network events)
In metrics API, user needs to configure explicitly which list field needs to be "flattened", in order to be consumable as filters/labels.
Nested fields can be consumed as filters/labels with the ">" character;
E.g: `flatten: [networkEvents], filters: [{key: "networkEvents>type", value: "acl"}], labels: [networkEvents>name]` This is a sample config to filter a metric for ACL events and label it by name
n/a
=> NETOBSERV-1935: enable metrics from list/nested fields

.tekton/pipeline-ref.yaml, contrib/docker/Dockerfile.downstream
Fixing version in downstream builds
n/a
=> Fixing version in downstream builds

docs/api.md, pkg/api/transform_filter.go, pkg/pipeline/encode/metrics/preprocess.go, pkg/pipeline/encode/metrics/preprocess_test.go, pkg/pipeline/transform/transform_filter.go, pkg/pipeline/transform/transform_filter_test.go, pkg/utils/convert.go, pkg/utils/filters/filters.go, pkg/utils/filters/filters_test.go
- Allow to define filters for keeping flows. These rules are processed separately as the logic is reverse (first match means it's kept)
- Allow sampling within these new rules
- Allow regex checks (pre-compiled; need to check error on preprocess)
n/a
=> NETOBSERV-1692: allow KEEP filtering logic

docs/api.md, pkg/api/transform_network.go, pkg/pipeline/transform/transform_network.go, pkg/utils/tcp_flags.go, pkg/utils/tcp_flags_test.go
Introduces new transform rule "decode_tcp_flags" that allows to convert a uint46 flag (e.g: 2) into its strings list representation (eg. "SYN")
More PRs are necessary for the full feature in netobserv but this one can be merged alone independently
=> NETOBSERV-1890: decode TCP flags (new stage/rule)

.tekton/pipeline-ref.yaml, contrib/docker/Dockerfile.downstream
Fix version in konfluxbuild.
Add required rpms scan task.
n/a
=> Fix version in konflux build

docs/api.md, pkg/api/transform_network.go, pkg/pipeline/transform/kubernetes/cni/multus.go, pkg/pipeline/transform/kubernetes/cni/udn.go, pkg/pipeline/transform/kubernetes/cni/udn_test.go, pkg/pipeline/transform/kubernetes/enrich_test.go, pkg/pipeline/transform/kubernetes/informers/informers-mock.go, pkg/pipeline/transform/kubernetes/informers/informers.go
Use the OVN annotation "k8s.ovn.org/pod-networks" to index pods  based on their IP + UDN label.
This is only enabled when SecondaryNetworks is configured with the "udn" index.
It leverages the "Udns" field that the ebpf agent populates, to find udn labels per flow. This should allow indexing with overlapping IPs.
It also populates the Src/Dst Network Name with the matched UDN label.
n/a
=> NETOBSERV-1904: Enrich using UDN info

go.mod, go.sum, pkg/pipeline/encode/encode_prom_test.go, pkg/pipeline/encode/metrics/flattening.go, pkg/pipeline/encode/metrics/preprocess_test.go, vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/proto.go, vendor/modules.txt
Ref: https://github.com/netobserv/flowlogs-pipeline/pull/802
=> NETOBSERV-2084: get nested data as native maps [backport 1.8]

pkg/kafka/reader.go, pkg/kafka/writer.go, pkg/pipeline/encode/encode_kafka.go, pkg/pipeline/ingest/ingest_kafka.go, pkg/pipeline/ingest/ingest_kafka_test.go, pkg/pipeline/transform/kubernetes/datasource/datasource.go, pkg/pipeline/transform/kubernetes/enrich.go, pkg/pipeline/transform/kubernetes/enrich_test.go, pkg/pipeline/transform/kubernetes/informers/config.go, pkg/pipeline/transform/kubernetes/informers/informers-mock.go, pkg/pipeline/transform/kubernetes/informers/informers.go, pkg/pipeline/transform/kubernetes/informers/informers_test.go, pkg/pipeline/transform/kubernetes/model/model.go, pkg/pipeline/transform/transform_network.go
Related: https://github.com/netobserv/flowlogs-pipeline/pull/681
This is a preliminary work preparing the ground for NETOBSERV-1248. No functional change here.
The goal is to minimize rebase hassle in #681
Details:
- Kafka read/write logic extracted from ingest/encode pipelines and put
into a dedicated kafka package
- New k8s "datasource" struct for k8s enrichment - currently only has
the usual informers datasource, but later will include a kafka-based
datasource as well
- Config related to k8s datasource moved into its own package. It
includes the SecondaryNetwork config.
- Some minor variables/functions renaming
n/a
* QE …
=> Refactoring prior to informers-cache rework

pkg/pipeline/ingest/ingest_collector.go, pkg/pipeline/ingest/ingest_collector_test.go
Fixes https://github.com/netobserv/flowlogs-pipeline/issues/940
cc @Nachtfalkeaw
=> NetFlow/IPFIX: render sampler address as string

pkg/api/transform_filter.go, pkg/pipeline/transform/transform_filter.go, pkg/pipeline/transform/transform_filter_test.go
Sampling field is added or modified in flows when a filtering rule with sampling is matched.
- If the sampling field wasn't set from the ebpf agent, the field is created with the new rule value
- If the sampling field was already set, the field is modified with new value = old value multiplied by FLP rule value.
n/a
=> NETOBSERV-2186: Set sampling in flows

pkg/pipeline/transform/kubernetes/cni/udn.go, pkg/pipeline/transform/kubernetes/cni/udn_test.go, pkg/pipeline/transform/kubernetes/informers/informers.go
When pod annotations are processed to get the UDN info, check whether it's a known cluster/namespace UDN; if cluster, we drop the namespace part that OVN writes in the annotation.
Operator: https://github.com/netobserv/network-observability-operator/pull/1508
=> NETOBSERV-2254: Disambiguate cluster udn and namespaced udn

docs/api.md, pkg/api/ingest_collector.go, pkg/pipeline/ingest/ingest_collector.go
Fixes #951 (partly)
Note that this PR doesn't affect netobserv operator, which doesn't use ipfix/netflow as an input
Example:
```yaml
ingest:
type: collector
collector:
hostName: localhost
port: 2055
workers: 8
sockets: 4
```
=> Expose goflow2 workers and sockets config

docs/api.md, pkg/api/write_loki.go, pkg/pipeline/write/write_loki.go, pkg/pipeline/write/write_loki_test.go, pkg/pipeline/write/write_stdout.go, pkg/pipeline/write/write_stdout_test.go
- Implement same formats as stdout writer (printf, json, fields)
- Allow reordering json keys
- Refactor and add more tests
Fixes #941 
Examples:
To send logs as plain go structures:
```yaml
write:
type: loki
loki:
format: printf
```
To send logs as ordered json
```yaml
write:
type: loki
loki:
format: json
reorder: true
```
=> Implement more format on Loki writer

go.mod, go.sum, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/encode_prom_test.go, pkg/pipeline/encode/metrics_common.go, pkg/pipeline/encode/opentelemetry/encode_otlpmetrics.go, pkg/pipeline/extract/aggregate/aggregate.go, pkg/pipeline/extract/aggregate/aggregate_test.go, pkg/pipeline/transform/transform_network.go, pkg/pipeline/utils/fnv.go, pkg/pipeline/utils/timed_cache.go, vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/model/packet_record.go, vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/model/record.go, vendor/modules.txt
In timed_cache, use uint64 hash (fnv 64a) instead of string builder
Uses the same implementation as in prom go client
Also:
- [Bump agent, with improved pb decode](https://github.com/netobserv/flowlogs-pipeline/pull/992/commits/a8e13410001541b7ab48dcab3dac4a0e8e313b20)
- [reduce allocations in metrics encode](https://github.com/netobserv/flowlogs-pipeline/pull/992/commits/da2f2679d60fab7c2cca388004928305e4a3f18f)
=> NETOBSERV-2285: opt: use uint64 hash instead of string for cache key

pkg/pipeline/transform/kubernetes/cni/multus.go, pkg/pipeline/transform/kubernetes/cni/multus_test.go, pkg/pipeline/transform/kubernetes/enrich_test.go, pkg/pipeline/transform/kubernetes/informers/informers_test.go
mac is now lower case in flows - make sure both key and lookup input are lower-cased
n/a
_To run a perfscale test, comment with: `/test flp-node-density-heavy-25nodes`_
=> NETOBSERV-2288: Fix MAC enrichment

Makefile
hey @OlivierCazade @jpinsonneau 
coverage jobs have been regularly failing recently (e.g. https://github.com/netobserv/flowlogs-pipeline/actions/runs/15996802014/job/45121983616 ) , apparently there's a conflict somehow with goyacc.
Removing all `yaccpar` lines makes it happy.
=> Fix go cover broken with goyacc

pkg/pipeline/ingest/ingest_grpc.go, pkg/pipeline/ingest/ingest_ipfix.go, pkg/pipeline/ingest/ingest_kafka.go, pkg/pipeline/ingest/metrics.go
Also, do not expose unused metrics, such as stage duration with ipfix collector
Fixes #1032
=> Add ingest count and latency metrics for ipfix collector

docs/api.md, docs/filtering.md, pkg/api/transform_filter.go
Just doc/text renamings...
n/a
_To run a perfscale test, comment with: `/test flp-node-density-heavy-25nodes`_
=> NETOBSERV-2355: Rename sampling ratio/rate -> interval

contrib/docker/Dockerfile.downstream
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
=> chore(KONFLUX-6210): fix and set name and cpe label for flowlogs-pipeline-zstream

docs/api.md, pkg/api/encode_prom.go, pkg/pipeline/encode/encode_prom.go, pkg/pipeline/encode/opentelemetry/encode_otlpmetrics.go
Expose prometheus HELP information to API `MetricsItem`.
n/a
=> Expose prometheus HELP information
