netobserv/flowlogs-pipeline

- contrib/kubernetes/flowlogs2metrics.conf.yaml
- docs/metrics.md
- pkg/confgen/confgen.go
- pkg/confgen/dedup.go
- pkg/confgen/dedup_test.go
> Add dedupe

- contrib/kubernetes/flowlogs2metrics.conf.yaml
- docs/metrics.md
- network_definitions/bandwidth_per_network_service.yaml
- network_definitions/bandwidth_per_src_dest_subnet.yaml
- network_definitions/bandwidth_per_src_subnet.yaml
- network_definitions/connection_rate_per_dest_subnet.yaml
- network_definitions/connection_rate_per_src_subnet.yaml
- network_definitions/connection_rate_per_tcp_flags.yaml
- network_definitions/connections_per_dst_as.yaml
- network_definitions/connections_per_src_as.yaml
- network_definitions/count_per_src_dest_subnet.yaml
- network_definitions/egress_bandwidth_per_dest_subnet.yaml
- network_definitions/egress_bandwidth_per_namespace.yaml
- network_definitions/geo-location_rate_per_dest.yaml
- network_definitions/mice_elephants.yaml
- network_definitions/network_services_count.yaml
- pkg/pipeline/encode/encode_prom.go
- pkg/pipeline/extract/aggregate/aggregate.go
- pkg/test/utils.go
Fixes #61
I implemented a variation of option (1). Rather than adding a delta field as suggested, I added a slice with the raw values since the last report. This approach allowed my to add a missing part in the Histogram support.
> Change gauges to counters

- README.md
> updated README to include new config structure

- pkg/pipeline/transform/kubernetes/cni/ovn_kubernetes.go
- pkg/pipeline/transform/kubernetes/cni/ovn_kubernetes_test.go
- pkg/pipeline/transform/kubernetes/kubernetes.go
- pkg/pipeline/transform/kubernetes/kubernetes_test.go
Fixes #217
It considerably reduces the number of unmatched IPs with OVN
> Detect ovn mp0 traffic

- pkg/pipeline/transform/transform_filter.go
- pkg/pipeline/transform/transform_network.go
> Copy maps before write

- pkg/api/encode_kafka.go
- pkg/api/ingest_kafka.go
- pkg/api/tls.go
- pkg/config/pipeline_builder_test.go
- pkg/pipeline/encode/encode_kafka.go
- pkg/pipeline/encode/encode_kafka_test.go
- pkg/pipeline/ingest/ingest_kafka.go
- pkg/pipeline/ingest/ingest_kafka_test.go
- pkg/test/tls.go
- pkg/test/utils.go
- Add API / config
- Read certificates / prepare TLS config for HTTP transport
- Use in ingester + encoder
> NETOBSERV-397 Kafka TLS

- Makefile
We changed the skipWithlabels to skipWithTags, but we missed it in one place in the Makefile.
> changed Labels to Tags

- pkg/api/ingest_kafka.go
After review, I did not change the yaml name, this fix it.
> Fix PullQueueCapacity marshalling

- pkg/operational/metrics/metrics.go
- pkg/pipeline/pipeline_builder.go
- pkg/pipeline/transform/transform_network.go
- pkg/pipeline/write/write_loki.go
- pkg/pipeline/write/write_loki_test.go
- pkg/test/loki_mock.go
- parallel transforms
- minor loki writer optimizations (pre-compute a couple of things)
- add loki benchmark
- add stage measurment metric
> NETOBSERV-577 Few FLP optimizations

- .github/workflows/pull_request.yml
- .github/workflows/push_image.yml
- .github/workflows/push_image_pr.yml
- .github/workflows/release.yml
- Makefile
Removed basename command in makefile and switched to docker because of podman version in github runner
> Fix release multiarch

- .github/workflows/push_image.yml
> Removed unused step

- pkg/utils/convert.go
- pkg/utils/convert_test.go
> Test ConvertToBool

- pkg/pipeline/transform/transform_network.go
Backport of https://github.com/netobserv/flowlogs-pipeline/pull/430
> [Backport] NETOBSERV-915 skip reinterpret direction for conversations

- pkg/config/config_test.go
> Add test covering use of viper with unmarshaller

- README.md
- contrib/kubernetes/flowlogs-pipeline.conf.yaml
- network_definitions/bandwidth_per_network_service.yaml
- network_definitions/bandwidth_per_src_dest_subnet.yaml
- network_definitions/bandwidth_per_src_subnet.yaml
- network_definitions/connection_rate_per_dest_subnet.yaml
- network_definitions/connection_rate_per_src_subnet.yaml
- network_definitions/count_per_src_dest_subnet.yaml
- network_definitions/egress_bandwidth_per_dest_subnet.yaml
- network_definitions/egress_bandwidth_per_namespace.yaml
- network_definitions/flows_length_histogram.yaml
- network_definitions/geo-location_rate_per_dest.yaml
- network_definitions/network_services_count.yaml
- pkg/api/api.go
- pkg/api/encode_prom.go
- pkg/confgen/confgen.go
- pkg/confgen/transform.go
- pkg/config/pipeline_builder_test.go
- running `make generate-configuration`
- remove unused AddIfRuleType
- renamed parseTransport -> parseTransform
- add omitempty to some api
> update examples, minor changes

- .tekton/flowlogs-pipeline-pull-request.yaml
- .tekton/flowlogs-pipeline-push.yaml
> Remove base image param in konflux config

- .tekton/flowlogs-pipeline-1-7-push.yaml
> Fix nudges configuration in konflux

- .tekton/pipeline-ref.yaml
Added new rpms-check image
n/a
> Added new rpms-check image

- .tekton/pipeline-ref.yaml
> KONFLUX Fix source build tagging

- .tekton/pipeline-ref.yaml
> Fix konflux results

- .tekton/pipeline-ref.yaml
> Removing deprecated results

- .tekton/flowlogs-pipeline-1-8-push.yaml
> Adding nudge configuration to 1.8 branch

- contrib/docker/Dockerfile.downstream
Backport of https://github.com/netobserv/flowlogs-pipeline/pull/820
> FIPS compliance [1.8 backport]

- .github/workflows/release.yml
- Makefile
- contrib/docker/Dockerfile
> Disable cgo on upstream builds and attach binaries to releases

- docs/api.md
- pkg/api/write_loki.go
> Document Loki client config
